# MariaDB testing server
# (Didn't feel like setting up XAMPP since it didn't have a NixOS package)
version: '3.1'
services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
      MARIADB_DATABASE: Tasks
    ports:
      - "3306:3306"
